GET http://localhost:8080/api/v1/test

{}
###
GET http://localhost:8080/api/v1/reactivTest

{}
###
GET http://localhost:8080/api/v1/addressbooks

{}
###
GET http://localhost:8080/api/v1/addressbooks?page=0&size=2

{}
###
GET http://localhost:8080/api/v1/transactionsave

{}
###
POST http://localhost:8080/api/v1/addresbook
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Ivanov",
  "phone": "+799999999999",
  "birthday": "2000-01-01"
}
